name: Unity PC Build

on:
  workflow_call:
    inputs:
      repository:
        description: Repository hosting the project
        type: string
        default: ${{ github.repository }}
        required: false
      ref:
        description: Reference to checkout
        type: string
        required: false
      project-version:
        description: Location of ProjectVersion.txt (if needed)
        type: string
        required: false
      binary-name:
        description: Name of the output binary
        type: string
        required: true
      google-folder-id:
        description: Id of the Google drive folder for upload
        type: string
        required: true
      runner:
        description: Runner to use for the build
        type: string
        required: false
        default: 'self-hosted'
      container-cpu-count:
        description: Number of CPUs to use for the build (blank means use all available)
        type: string
        required: false
      container-memory:
        description: Amount of memory (GB) for container (blank means use all available)
        type: string
        required: false
      slack-channel:
        description: (Optional) Slack channel to post build notifications
        type: string
        required: false


concurrency: ${{ inputs.repository }}

jobs:
  # Find a runner, and sync the project
  sync-project:
    name: Sync project
    runs-on: ${{ inputs.runner }}
    outputs:
      runner-name: ${{ runner.name }}
    steps:
      - name: Kill any existing builds
        run: |
          docker rm -f pew-unity-builder

      - name: Remove any old build artifacts
        run: |
          if (Test-Path -Path '${{ github.workspace }}\builds') {
            Remove-Item -Path '${{ github.workspace }}\builds' -Recurse -Force -Verbose
          }

      - id: app-installation
        name: Find builder installation for ${{ inputs.repository }}
        uses: PlayEveryware/action-find-app-installation@v1
        with:
          private-key: ${{ secrets.PEW_BUILDER_KEY_EL9FMYV8DVTLYMLSZJZRVL569RFZWPS }}
          repository: ${{ inputs.repository }}

      - id: lfs-cache-server
        name: Determine the GitHub LFS cache server to use
        run: |
          $match = ( echo "${{ inputs.repository }}" | `
            Select-String -Pattern "^PlayEveryWare/.*$" )
          if ( $match ) {
            Add-Content -Path "$ENV:GITHUB_OUTPUT" -Encoding ascii -Value "value=https://lfscache.office.playeveryware.com/${{ inputs.repository }}"
          }

      - id: app-token
        name: Acquire builder installation token for ${{ inputs.repository }}
        uses: PlayEveryWare/action-app-installation-pat@v1
        with:
          installation-id: ${{ steps.app-installation.outputs.installation-id }}
          private-key: ${{ secrets.PEW_BUILDER_KEY_EL9FMYV8DVTLYMLSZJZRVL569RFZWPS }}
          repositories: ${{ inputs.repository }}

      - name: Checkout the project repository
        uses: PlayEveryWare/checkout@v1
        id: checkout
        with:
          repository: ${{ inputs.repository }}
          token: ${{ steps.app-token.outputs.token }}
          path: title
          ref: ${{ inputs.ref }}
          lfs: true
          lfs-url: ${{ steps.lfs-cache-server.outputs.value }}
          clean-exclude: /**/Library/

  # Gerenrate the build environemnt needed for the project
  prepare:
    name: Prepare build environment
    runs-on: ${{ needs.sync-project.outputs.runner-name }}
    needs: sync-project
    outputs:
      runner-name: ${{ runner.name }}
      image-name: ${{ steps.info.outputs.image-name }}
      library-folder-exists: ${{ steps.info.outputs.library-folder-exists }}
      project-path: ${{ steps.info.outputs.project-path }}
      name-short: ${{ steps.build-name.outputs.short }}
      build-name-pc: ${{ steps.build-name.outputs.pc }}
      thread-ts: ${{ steps.slack.outputs.ts }}
      thread-channel: ${{ steps.slack.outputs.channel_id }}
      actor: ${{ github.actor }}
    steps:
      - id: build-name
        name: Generate build artifact names
        uses: PlayEveryWare/action-create-build-name@v3
        with:
          project-name: ${{ inputs.binary-name }}
          branch-name: ${{ inputs.ref }}
          repository-path: title
          build-configuration: RELEASE

      - id: info
        name: Get Unity project information
        uses: PlayEveryWare/action-unity-info@v1
        with:
          path: title
          project-version: ${{ inputs.project-version }}

      - id: slack
        if: inputs.slack-channel != ''
        name: Notify slack build is starting
        uses: playeveryware/action-slack@v1-pew
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ inputs.slack-channel }}
          slack-message: ":waiting: Build `${{ steps.build-name.outputs.short }}` started by `${{ github.actor }}` from branch `${{ github.ref_name }}`"

      - name: Notify slack of build logs
        uses: playeveryware/action-slack@v1-pew
        if: inputs.slack-channel != ''
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ inputs.slack-channel }}
          payload: |
            {
              "text": "See logs at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "thread_ts": "${{ steps.slack.outputs.ts }}"
            }

      - name: Dump Unity project information
        run: |
          echo "Project path: '${{ steps.info.outputs.project-path }}'"
          echo "Unity version: '${{ steps.info.outputs.unity-version }}'"
          echo "Unity changeset: '${{ steps.info.outputs.unity-changeset }}'"
          echo "Library folder exists: '${{ steps.info.outputs.library-folder-exists }}'"
          echo "Image name: '${{ steps.info.outputs.image-name }}'"
          echo "Image exists: '${{ steps.info.outputs.image-exists }}'"

      - name: Checkout pew-docker repository
        if: steps.info.outputs.image-exists != 'true'
        uses: PlayEveryWare/checkout@v1
        with:
          repository: PlayEveryWare/pew-docker
          path: .pew-builder/pew-docker

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Create and push Unity Image
        if: steps.info.outputs.image-exists != 'true'
        run: |
          echo "::warning::Unity image for ${{ steps.info.outputs.unity-version }} does not exist. Building it now..."

          docker build `
            --build-arg UNITY_VERSION=${{ steps.info.outputs.unity-version }} `
            --build-arg UNITY_CHANGESET=${{ steps.info.outputs.unity-changeset }} `
            -t ${{ steps.info.outputs.image-name }} `
            .pew-builder/pew-docker/unity

          docker push ${{ steps.info.outputs.image-name }}

      - name: Pull unity image
        run: |
          docker pull ${{ steps.info.outputs.image-name }}

  build-pc:
    name: Build PC
    needs: [sync-project, prepare]
    runs-on: ${{ needs.sync-project.outputs.runner-name }}
    outputs:
      runner-name: ${{ runner.name }}
      project-path: ${{ needs.prepare.outputs.project-path }}
    steps:
      - name: Log warning that asset import may take a while
        if: needs.prepare.outputs.library-folder-exists != 'true'
        run: |
          echo "::warning::No Library/ folder detected. Performing a fresh asset import"

      - name: Kill any existing builder
        run: |
          docker rm -f pew-unity-builder

      - name: Get host resources
        id: host-resources
        uses: playeveryware/action-host-cpumem@v1

      - name: Build PC package
        run: |
          docker run --rm `
            --name pew-unity-builder `
            --cpus=${{ inputs.container-cpu-count || steps.host-resources.outputs.cpu-count }} `
            --memory=${{ inputs.container-memory || steps.host-resources.outputs.memory-gb }}g `
            -v ${{ needs.prepare.outputs.project-path }}:C:\Source `
            ${{ needs.prepare.outputs.image-name }} `
            c:\Unity\Editor\Unity.exe `
            -batchmode `
            -nographics `
            -adb2 `
            -EnableCacheServer `
            -cacheServerEndpoint unityaccel.office.playeveryware.com `
            -cacheServerEnableDownload true `
            -cacheServerEnableUpload true `
            -projectPath c:\Source `
            -logFile C:\Source\log.txt `
            -buildWindows64Player C:\Source\build\${{ inputs.binary-name }}.exe `
            -username ${{ secrets.UNITY_EMAIL }} `
            -password ${{ secrets.UNITY_PASSWORD }} `
            -serial ${{ secrets.UNITY_SERIAL }} `
            -quit

          type ${{ needs.prepare.outputs.project-path }}\log.txt

  upload-pc-build:
    name: Upload PC build
    needs: [build-pc, prepare]
    runs-on: ${{ needs.build-pc.outputs.runner-name }}
    outputs:
      upload-pc: ${{ steps.pc-build.outputs.file-id }}
    env:
      build-name: ${{ needs.prepare.outputs.build-name-pc }}
    steps:
      - name: Archive build
        run: |
          pushd ${{ needs.build-pc.outputs.project-path }}
          tar `
            --strip-components=1 `
            -a -c -v `
            -f "${{ env.build-name }}" `
            build

          if (!(Test-Path -Path '${{ github.workspace }}\builds')) {
            New-Item -Path '${{ github.workspace }}\builds' -ItemType Directory
          }

          move '${{ env.build-name }}' '${{ github.workspace }}\builds\'
          popd

      - name: Upload build to Google Drive
        id: pc-build
        uses: PlayEveryWare/action-google-drive-upload@v1
        with:
          credentials: ${{ secrets.GOOGLE_UPLOAD_CREDENTIALS }}
          parent_folder_id: ${{ inputs.google-folder-id }}
          target: ${{ github.workspace }}\builds\${{ env.build-name }}
          name: ${{ env.build-name }}

      - name: Note the build file name
        run: |
          echo "::notice title=Build Artifact::Uploaded PC build as ${{ env.build-name }}"

  notify-slack:
    name: 'Notify slack of build result'
    runs-on: [self-hosted]
    needs: [prepare, build-pc, upload-pc-build]
    if: ${{ always() && needs.prepare.outputs.thread-ts }}
    steps:
      - name: Notify slack build has completed
        if: ${{ contains(needs.upload-pc-build.result, 'success') }}
        uses: playeveryware/action-slack@v1-pew
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ needs.prepare.outputs.thread-channel }}
          slack-message: ":white_check_mark: Build `${{ needs.prepare.outputs.name-short }}` completed. Started by `${{ needs.prepare.outputs.actor }}` from branch `${{ github.ref_name }}`\n * PC: <https://drive.google.com/file/d/${{ needs.upload-pc-build.outputs.upload-pc }}/view?usp=share_link|${{ needs.prepare.outputs.build-name-pc }}>"
          update-ts: ${{ needs.prepare.outputs.thread-ts }}

      - name: Notify slack build has failed
        if: ${{ contains(needs.*.result, 'failure') }}
        uses: playeveryware/action-slack@v1-pew
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ needs.prepare.outputs.thread-channel }}
          slack-message: ":x: Build `${{ needs.prepare.outputs.name-short }}` has failed. Started by `${{ needs.prepare.outputs.actor }}` from branch `${{ github.ref_name }}`\n * Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          update-ts: ${{ needs.prepare.outputs.thread-ts }}

      - name: Notify slack build was canceled
        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.upload-pc-build.result, 'success') }}
        uses: playeveryware/action-slack@v1-pew
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ needs.prepare.outputs.thread-channel }}
          slack-message: ":heavy_multiplication_x: Build `${{ needs.prepare.outputs.name-short }}` has been cancelled. Started by `${{ needs.prepare.outputs.actor }}` from branch `${{ github.ref_name }}`"
          update-ts: ${{ needs.prepare.outputs.thread-ts }}
